from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pytest


def _run(cmd: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        cmd,
        capture_output=True,
        text=True,
        check=False,
    )


def _failure_context(
    label: str,
    proc: subprocess.CompletedProcess[str],
) -> str:
    return (
        f"\n{label} failed"
        f"\nreturn code: {proc.returncode}"
        f"\nstdout:\n{proc.stdout}"
        f"\nstderr:\n{proc.stderr}"
    )


def test_generator_to_diagnostics_pipeline(
    tmp_path: Path,
    generator_script: Path,
    diagnostics_script: Path,
    read_report_json,
) -> None:
    """
    End-to-end regression test for the core Grid Suite workflow.

    A grid generated by the current generator must be accepted by the current
    diagnostics utility with no critical failures.
    """
    grid = tmp_path / "pipeline_grid.nc"
    reports = tmp_path / "reports"

    generator_cmd = [
        sys.executable,
        str(generator_script),
        "--outfile",
        str(grid),
        # Use the normal Grid Suite radial resolution here rather than the
        # deliberately tiny smoke-test resolution. nx=68 gives 64 interior
        # points with MXG=2 and avoids a legitimate coarse-resolution warning.
        "--nx",
        "68",
        "--ny",
        "32",
        "--nz",
        "8",
        "--R0",
        "6.2",
        "--a",
        "2.0",
        "--kappa",
        "1.7",
        "--delta",
        "0.33",
        "--q0",
        "1.05",
        "--qa",
        "3.5",
    ]

    generated = _run(generator_cmd)

    assert generated.returncode == 0, _failure_context(
        "Grid generator",
        generated,
    )
    assert grid.is_file(), f"Generator did not create expected grid: {grid}"
    assert grid.stat().st_size > 0, "Generated pipeline grid is empty."

    diagnostics_cmd = [
        sys.executable,
        str(diagnostics_script),
        str(grid),
        "--outdir",
        str(reports),
        "--json-only",
        "--quiet",
    ]

    diagnosed = _run(diagnostics_cmd)

    assert diagnosed.returncode == 0, _failure_context(
        "Grid diagnostics",
        diagnosed,
    )

    report = reports / f"{grid.stem}_report.json"
    assert report.is_file(), f"Expected diagnostic report was not created: {report}"

    payload = read_report_json(report)

    assert isinstance(payload.get("checks"), list)
    assert isinstance(payload.get("critical_failures"), list)
    assert isinstance(payload.get("warnings"), list)

    assert payload["critical_failures"] == [], (
        "Grid generated by the current generator was rejected by the current "
        f"diagnostics utility: {payload['critical_failures']}"
    )

    failed_warn_checks = [
        check
        for check in payload["checks"]
        if check.get("severity") == "WARN" and check.get("status") == "FAIL"
    ]
    assert failed_warn_checks == [], (
        "Baseline generated grid produced failed WARN checks: "
        f"{failed_warn_checks}"
    )
    assert payload["warnings"] == [], (
        "Baseline generated grid produced top-level warnings: "
        f"{payload['warnings']}"
    )

    assert payload.get("nx") == 68
    assert payload.get("ny") == 32
    assert payload.get("nz") == 8

    # Geometry diagnostics must agree with the parameters supplied to the
    # generator. This guards against mixing a radial line with global extents.
    assert payload.get("R0") == pytest.approx(6.2, abs=1e-6)
    assert payload.get("a") == pytest.approx(2.0, abs=1e-6)
    assert payload.get("kappa") == pytest.approx(1.7, abs=1e-6)
    assert payload.get("delta") == pytest.approx(0.33, abs=5e-3)
    assert payload.get("aspect_ratio") == pytest.approx(3.1, abs=1e-6)
    assert payload.get("config_type") == "CLOSED_CORE / NO X-POINT"

    # Canonical BOUT++ 5.x contract must be satisfied, not merely a
    # self-consistent reversed/forensic metric convention.
    assert payload.get("bout5_compatible") is True
    assert payload.get("bout5_metric_naming") == "CANONICAL"
    assert payload.get("bout5_j_max_rel_error", 1.0) < 1e-8
    assert payload.get("bout5_bxy_max_rel_error", 1.0) < 1e-8
    assert payload.get("bout5_shift_torsion_present") is True
    assert payload.get("bout5_shift_torsion_finite") is True

    toroidal_metric_checks = [
        check
        for check in payload["checks"]
        if check.get("name") == "geometry:covariant_toroidal_metric_matches_R2"
    ]
    assert len(toroidal_metric_checks) == 1
    assert toroidal_metric_checks[0].get("status") == "PASS"
    assert toroidal_metric_checks[0].get("details", {}).get("metric_variable") == "g_33"
